#ifndef _DEEPOON_POLARIS_ROOM_SETUP_COMMON_H_
#define _DEEPOON_POLARIS_ROOM_SETUP_COMMON_H_

#include <string>

enum STATION_MASK
{
	DPNPD_SETUP_STATION_A = 1 << 0,
	DPNPD_SETUP_STATION_B = 1 << 1
};

enum
{
	DPNP_SETUP_RESULT_OK = 0, // Success. 成功。
	DPNP_SETUP_RESULT_FAIL, // failed. 失败。

	DPNP_SETUP_RESULT_STATION_OFF, // Station is off. 基站关闭。
	DPNP_SETUP_RESULT_STATION_ON, // Station is on. 基站开启。
	DPNP_SETUP_RESULT_STATION_CALIBRATED, // Station is calibrated. 基站已经校准。

	DPNP_SETUP_RESULT_PARAMETER_WRONG_DEVICE_TYPE = 100,
	DPNP_SETUP_RESULT_PARAMETER_INVALID_STATION_INDEX,
	DPNP_SETUP_RESULT_PARAMETER_NULL_POINTER,

	DPNP_SETUP_RESULT_NOT_INITIALIZED = 200, // 需要先调用DpnpSetupInit
	DPNP_SETUP_RESULT_CAUGHT_AN_EXCEPTION,
	DPNP_SETUP_RESULT_FAILED_TO_LOAD_ROOM_INFO,

	DPNP_SETUP_RESULT_THREAD_EXISTS = 300,
	DPNP_SETUP_RESULT_THREAD_RESOURCE_UNAVAILABLE_TRY_AGAIN,
	DPNP_SETUP_RESULT_THREAD_CAUGHT_AN_EXCEPTION,

	DPNP_SETUP_RESULT_CALIBRATION_ABORT = 400,
	DPNP_SETUP_RESULT_SPACE_TOO_SMALL,
	DPNP_SETUP_RESULT_ROOM_INFO_BAD_SAVE,
	DPNP_SETUP_RESULT_NOT_SIMPLE_CONVEX, // 不是一个凸四边形

	////////////////////////////////////////////////////////////////////////////////////////////////////////////

	DPNP_SETUP_RESULT_DDK_DEFINITION_BEGIN = 1000, // Below are DDK implementation-defined enum:
	DPNP_SETUP_RESULT_DDK_DEVICE_OUT_OF_SIGHT, // Device out of sight of the station 设备不在基站可见范围内。
	DPNP_SETUP_RESULT_DDK_DEVICE_CONNECTION_LOST, // Device connection lost. 连接设备失败。
	DPNP_SETUP_RESULT_DDK_STATIONS_NOT_CALIBRATED, // Stations are not calibrated. 基站尚未校准。
	DPNP_SETUP_RESULT_DDK_CONDITION_CALIBRATION_IN_PROGRESS, // Calibration in progress. 基站正被校准。
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NOT_STABLE, // Controller not stable. 采集失败。手柄没有被稳定摆放，或者中途被移动，抛弃此数据重新摆放并采集。
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_POSE_CHANGE, // Controller pose change. 采集失败。手柄摆放姿态与第一次摆放有极大不同，无法保证校准结果，抛弃此数据重新摆放并采集。
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_TOO_CLOSE, // Controller too close. 采集失败。手柄摆放位置与前几次摆放过于接近，无法保证校准结果，抛弃此数据重新摆放并采集。

	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_BE_SEEN_TOGETHER, // Controller cannot be seen together. 采集失败。手柄摆放位置无法被基站同时看到，无法保证校准结果，抛弃此数据重新摆放并采集。
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_LIGHT_SEEN_IN_COMMON, // controller has no light been seen across CALIBRATION_DATA_COLLECTION_COUNT points for a same station. 采集失败。手柄摆放不同位置无法被同一基站看到同一盏灯，无法保证校准结果，抛弃此数据重新摆放并采集。
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_ENOUGH_LIGHTS_SEEN, // controller has not enough lights seen. 采集失败。手柄摆放位置无法被任一基站看到二盏灯以上，无法保证校准结果，抛弃此数据重新摆放并采集。

	DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_TRIGGER_RELEASE, // Wait for trigger release. 等待所有手柄的扳机放开。
	DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_NEXT_INPUT, // Wait for next input. 准备完成。摆放下一位置并采集。
	DPNP_SETUP_RESULT_DDK_WRONG_STATION_ROLE, // Wrong station role. 基站角色不符，需将拨码开关拨到正确位置。
	DPNP_SETUP_RESULT_DDK_INVALID_DATA, // Invalide data. 数据无效。
	DPNP_SETUP_RESULT_DDK_STATION_SN_DUPLICATED, // Station SN duplicated. 从基站和主基站序列号相同。
	DPNP_SETUP_RESULT_DDK_GET_GROUND_HEIGHT_FAILED, // 基站校准最后一步: 获取手柄位置失败, 无法计算基站距地面的高度

	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_A,  //无法保证A基站至少在4个位置看到同一个灯
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_B,  //无法保证B基站至少在4个位置看到同一个灯
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_AB, //无法保证A、B基站至少在2个位置看到同一个灯
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RETRY_A, //单基站，看不到灯 
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RETRY_B, //单基站，看不到灯
	//DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RETRY_AB, // 双基站，8个位置后，依然Fail，重采一次
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_A, //单基站，从第一个位置开始重新采集 
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_B,//单基站，从第一个位置开始重新采集
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_AB,//双基站，从第一个位置开始重新采集

	DPNP_SETUP_RESULT_DDK_NO_DUAL_BASESTATION_PARAMETER,  //校正双基站，但没有双基站参数
	DPNP_SETUP_RESULT_DDK_NO_B_BASESTATION_PARAMETER,     //没有B基站参数
	DPNP_SETUP_RESULT_DDK_NO_A_BASESTATION_PARAMETER,     //没有A基站参数
	DPNP_SETUP_RESULT_DDK_DEVICE_HAND_CONNECTION_LOST,    //手柄不在可见范围内或者未开机
	DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_TRIGGER_INPUT,  //等待扣手柄扳机
	DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_COMMON_POINT,		//双基站没有同时看到1号灯
	DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_B_POINT,            //B基站看不到要求的灯，请将手柄优先放到B基站可见范围内
	DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_A_POINT,             //A基站看不到要求的灯，请将手柄优先放到A基站可见范围内
	DPNP_SETUP_RESULT_DDK_CONDITION_NO_COMMON_AREA_RAISE_RETRY_TWICE, //双基站在地面上没有共同覆盖区域，请将手柄放于空中重新采集2次
	DPNP_SETUP_RESULT_CALIBRATION_NEED_TRUE_BASECALIB_ID,           //请用户选择正确的校准基站：主基站（1），从基站（2），双基站（3）
	DPNP_SETUP_RESULT_DDK_CONDITION_NO_COMMON_AREA_RETRY_AIR_POINT, //空中采集时，此时刻位置未被正确采集，请重试
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_STABLE_1_LIGHT_SEEN,  //基站看不到灯，请重新放置

	DPNP_SETUP_RESULT_DDK_CANNOT_CAPTUREPOINT_WITHIN_FIVE_TIMES, //单个位置连续五次采集不到点
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_COMMON,  //没有看到共灯，请往中间位置摆放
	DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_X_TOO_CLOSE, //请沿垂直于基站连线方向摆放

	//NewCalib
	DPNP_NEW_CALIB_WAITFOR_PUSH_BUTTON, //等待用户点击按钮
	DPNP_NEW_CALIB_GET_PUSH_BUTTON,    //用户完成按钮点击

	DPNP_NEW_CALIB_BEGIN_CALIB,        //请正确放置手柄，并点击按钮，开始基站校准
	DPNP_NEW_CALIB_BEGIN_NEXT_CALIB,    //第一个点采集成功，请正确放置手柄，并点击按钮，开始采集第二个点
	DPNP_NEW_CALIB_FINISH_CAPTURE,      //完成数据采集,开始计算
	DPNP_NEW_CALIB_CONNECTION_LOST,     //手柄设备连接失败
	DPNP_NEW_CALIB_HAND_LOST,          //手柄不在校准区内或休眠
	DPNP_NEW_CALIB_POSE_CHANGE,        //手柄两次摆放姿态不一致
	DPNP_NEW_CALIB_HAND_SHAKE,         //手柄晃动，无法正确采集数据
	DPNP_NEW_CALIB_TOO_CLOSE,          //当前位置与上次摆放距离过近
	DPNP_NEW_CALIB_LOCATION_ERROR,      //摆放位置不对，请沿平行于基站连线方向摆放
	DPNP_NEW_CALIB_CANNT_CAPTURE_ENOUGH_DATA, //手柄无法正确采集数据
	DPNP_NEW_CALIB_POSE_CHANGE_LR,        //左右手柄摆放姿态不一致
	DPNP_NEW_CALIB_POSE_WRONG,        //手柄摆放姿态不对

	// this should always be the last one
	DPNP_SETUP_RESULT_NUM，
};

typedef int DPNP_SETUP_RESULT; // RoomSetup过程中的各函数的执行结果, 基站校准的状态

#define DPN_POLARIS_MIN_STABLE_MARKS_COUNT 2

#include <map>
inline std::string echo_en(DPNP_SETUP_RESULT err_no)
{
    const static std::map<DPNP_SETUP_RESULT, const std::string> err_msg{
        { DPNP_SETUP_RESULT_OK, "OK" },
        { DPNP_SETUP_RESULT_FAIL, "FAIL" },

        { DPNP_SETUP_RESULT_STATION_OFF, "STATION OFF" },
        { DPNP_SETUP_RESULT_STATION_ON, "STATION ON" },
        { DPNP_SETUP_RESULT_STATION_CALIBRATED, "STATION CALIBRATED" },

        { DPNP_SETUP_RESULT_PARAMETER_WRONG_DEVICE_TYPE, "PARAMETER WRONG DEVICE TYPE" },
        { DPNP_SETUP_RESULT_PARAMETER_INVALID_STATION_INDEX, "PARAMETER INVALID STATION INDEX" },
        { DPNP_SETUP_RESULT_PARAMETER_NULL_POINTER, "PARAMETER NULL POINTER" },

        { DPNP_SETUP_RESULT_NOT_INITIALIZED, "NOT INITIALIZED" },
        { DPNP_SETUP_RESULT_CAUGHT_AN_EXCEPTION, "CAUGHT AN EXCEPTION" },
        { DPNP_SETUP_RESULT_FAILED_TO_LOAD_ROOM_INFO, "FAILED TO LOAD ROOM INFO" },

        { DPNP_SETUP_RESULT_THREAD_EXISTS, "THREAD EXISTS" },
        { DPNP_SETUP_RESULT_THREAD_RESOURCE_UNAVAILABLE_TRY_AGAIN, "THREAD RESOURCE UNAVAILABLE TRY AGAIN" },
        { DPNP_SETUP_RESULT_THREAD_CAUGHT_AN_EXCEPTION, "THREAD CAUGHT AN EXCEPTION" },

        { DPNP_SETUP_RESULT_CALIBRATION_ABORT, "CALIBRATION ABORT" },
        { DPNP_SETUP_RESULT_SPACE_TOO_SMALL, "SPACE TOO SMALL" },
        { DPNP_SETUP_RESULT_ROOM_INFO_BAD_SAVE, "ROOM INFO BAD SAVE" },
        { DPNP_SETUP_RESULT_NOT_SIMPLE_CONVEX, "NOT SIMPLE CONVEX" },

        { DPNP_SETUP_RESULT_DDK_DEFINITION_BEGIN, "DDK DEFINITION BEGIN" },
        { DPNP_SETUP_RESULT_DDK_DEVICE_OUT_OF_SIGHT, "DDK DEVICE OUT OF SIGHT" },
        { DPNP_SETUP_RESULT_DDK_DEVICE_CONNECTION_LOST, "DDK DEVICE CONNECTION LOST" },
        { DPNP_SETUP_RESULT_DDK_STATIONS_NOT_CALIBRATED, "DDK STATIONS NOT CALIBRATED" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CALIBRATION_IN_PROGRESS, "DDK CONDITION CALIBRATION IN PROGRESS" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NOT_STABLE, "DDK CONDITION CONTROLLER NOT STABLE" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_POSE_CHANGE, "DDK CONDITION CONTROLLER POSE CHANGE" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_TOO_CLOSE, "DDK CONDITION CONTROLLER TOO CLOSE" },

        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_BE_SEEN_TOGETHER, "DDK CONDITION CONTROLLER CANNOT BE SEEN TOGETHER" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_LIGHT_SEEN_IN_COMMON, "DDK CONDITION CONTROLLER NO LIGHT SEEN IN COMMON" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_ENOUGH_LIGHTS_SEEN, "DDK CONDITION CONTROLLER NO ENOUGH LIGHTS SEEN" },

        { DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_TRIGGER_RELEASE, "DDK CONDITION WAIT FOR TRIGGER RELEASE" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_NEXT_INPUT, "DDK CONDITION WAIT FOR NEXT INPUT" },
        { DPNP_SETUP_RESULT_DDK_WRONG_STATION_ROLE, "DDK WRONG STATION ROLE" },
        { DPNP_SETUP_RESULT_DDK_INVALID_DATA, "DDK INVALID DATA" },
        { DPNP_SETUP_RESULT_DDK_STATION_SN_DUPLICATED, "DDK STATION SN DUPLICATED" },
        { DPNP_SETUP_RESULT_DDK_GET_GROUND_HEIGHT_FAILED, "DDK GET GROUND HEIGHT FAILED" },

        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_A, "DDK CONDITION CONTROLLER CANNOT COMPUTE A" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_B, "DDK CONDITION CONTROLLER CANNOT COMPUTE B" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_CANNOT_COMPUTE_AB, "DDK CONDITION CONTROLLER CANNOT COMPUTE AB" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RETRY_A, "DDK CONDITION CONTROLLER RETRY A" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RETRY_B, "DDK CONDITION CONTROLLER RETRY B" },

        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_A, "DDK CONDITION CONTROLLER RESET A" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_B, "DDK CONDITION CONTROLLER RESET B" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_RESET_AB, "DDK CONDITION CONTROLLER RESET AB" },

        { DPNP_SETUP_RESULT_DDK_NO_DUAL_BASESTATION_PARAMETER, "DDK NO DUAL BASESTATION PARAMETER" },
        { DPNP_SETUP_RESULT_DDK_NO_B_BASESTATION_PARAMETER, "DDK NO B BASESTATION PARAMETER" },
        { DPNP_SETUP_RESULT_DDK_NO_A_BASESTATION_PARAMETER, "DDK NO A BASESTATION PARAMETER" },
        { DPNP_SETUP_RESULT_DDK_DEVICE_HAND_CONNECTION_LOST, "DDK DEVICE HAND CONNECTION LOST" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_WAIT_FOR_TRIGGER_INPUT, "DDK CONDITION WAIT FOR TRIGGER INPUT" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_COMMON_POINT, "DDK CONDITION LACK OF COMMON POINT" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_B_POINT, "DDK CONDITION LACK OF B POINT" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_LACK_OF_A_POINT, "DDK CONDITION LACK OF A POINT" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_NO_COMMON_AREA_RAISE_RETRY_TWICE, "DDK CONDITION NO COMMON AREA RAISE RETRY TWICE" },
        { DPNP_SETUP_RESULT_CALIBRATION_NEED_TRUE_BASECALIB_ID, "CALIBRATION NEED TRUE BASECALIB ID" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_NO_COMMON_AREA_RETRY_AIR_POINT, "DDK CONDITION NO COMMON AREA RETRY AIR POINT" },
        { DPNP_SETUP_RESULT_DDK_CONDITION_CONTROLLER_NO_STABLE_1_LIGHT_SEEN, "DDK CONDITION CONTROLLER NO STABLE 1 LIGHT SEEN" }
    };

    auto it = err_msg.find(err_no);
    return it == err_msg.end() ? "Unknown" : it->second;
}
#endif // !_DEEPOON_POLARIS_ROOM_SETUP_COMMON_H_
